name: projeto_ble_renew
description: "Controle de fluxo de pessoas e equipamentos em hospital"
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.0
  flutter_blue_plus: ^1.31.17
  curved_labeled_navigation_bar: ^2.0.2
  internet_connection_checker: ^1.0.0+1
  image_picker: ^1.0.7
  mask_text_input_formatter: ^2.9.0
  uuid: ^4.4.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/codelink.png"
  adaptive_icon_background: '#292935'
  adaptive_icon_foreground: 'images/1024.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "images/codelink.png"
    icon_size: 48 # min:48, max:256, default: 48

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
